# Generated by Django 3.1.2 on 2020-10-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
