# Generated by Django 3.1.2 on 2020-10-13 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20201013_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='uploaded_by',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.device'),
        ),
    ]
