# Generated by Django 3.1.2 on 2020-10-14 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20201013_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
