# Generated by Django 3.1.2 on 2020-10-14 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_auto_20201014_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
    ]
