# Generated by Django 3.1.2 on 2020-10-14 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_remove_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
